import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Alert } from 'react-native';
import { useRouter } from 'expo-router';
import * as DocumentPicker from 'expo-document-picker';
import { PrimaryButton } from '../components/PrimaryButton';
import { DummyTomato } from '../components/DummyTomato';
import { UploadCard } from '../components/UploadCard';
import { useScanContext } from '../context/ScanContext';
import { WavelengthMeasurements } from '../types';
import { TomatoTheme } from '../constants/theme';

const MOCK_DEFAULT_JSON: WavelengthMeasurements = {
  '405': 0.33443,
  '450': 0.45163,
  '530': 0.59159,
  '660': 0.64213,
  '850': 0.49823,
  '940': 0.43046,
};

export default function InsertScreen() {
  const router = useRouter();
  const { setSensorMeasurements } = useScanContext();

  const [tabletAdded, setTabletAdded] = useState(false);
  const [selectedFileName, setSelectedFileName] = useState<string | null>(null);
  const [measurements, setMeasurements] = useState<WavelengthMeasurements | null>(null);

  const handlePickDocument = async () => {
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: 'application/json',
        copyToCacheDirectory: true,
      });

      if (!result.canceled && result.assets && result.assets.length > 0) {
        const file = result.assets[0];
        setSelectedFileName(file.name);

        // Fetch local file text (works cross-platform in Expo)
        const res = await fetch(file.uri);
        const jsonText = await res.text();
        const parsed = JSON.parse(jsonText);

        if (validateSensorJson(parsed)) {
          setMeasurements(parsed.measurements);
        } else {
          Alert.alert('Invalid Sensor JSON', 'Uploaded file must contain all 6 wavelength measurements.');
          setSelectedFileName(null);
        }
      }
    } catch (e) {
      // If user cancels or picker fails, allow loading sample demo JSON
      Alert.alert('File Picker', 'Using default demo JSON data for scan analysis.');
      setSelectedFileName('simulated_scan_paracetamol.json');
      setMeasurements(MOCK_DEFAULT_JSON);
    }
  };

  const validateSensorJson = (data: any): boolean => {
    if (!data || typeof data !== 'object') return false;
    if (!data.measurements || typeof data.measurements !== 'object') return false;

    const requiredWavelengths = ['405', '450', '530', '660', '850', '940'];
    return requiredWavelengths.every(
      (wl) => typeof data.measurements[wl] === 'number' && !isNaN(data.measurements[wl])
    );
  };

  const handleUseDemoJson = () => {
    setSelectedFileName('demo_paracetamol_500mg.json');
    setMeasurements(MOCK_DEFAULT_JSON);
  };

  const handleStartAnalysis = () => {
    const finalMeasurements = measurements || MOCK_DEFAULT_JSON;
    setSensorMeasurements(finalMeasurements);
    router.push('/scan');
  };

  return (
    <ScrollView contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
      {!tabletAdded ? (
        <View style={styles.section}>
          <Text style={styles.title}>Place Tablet</Text>
          <Text style={styles.instruction}>
            Drop the tablet into Tomato. The sample will be dissolved and optically analyzed.
          </Text>

          {/* Spherical Tomato hardware visual representation */}
          <DummyTomato isScanning={false} />

          <PrimaryButton
            title="Tablet Added"
            onPress={() => setTabletAdded(true)}
            style={styles.actionBtn}
          />
        </View>
      ) : (
        <View style={styles.section}>
          <Text style={styles.title}>Connect Scan Data</Text>
          <Text style={styles.instruction}>
            For this prototype, upload the simulated sensor data generated by Tomato.
          </Text>

          <UploadCard
            title="Upload Sensor JSON"
            subtitle="6 wavelength measurements"
            fileName={selectedFileName}
            onPress={handlePickDocument}
            style={styles.uploadCard}
          />

          {!measurements && (
            <Text style={styles.demoHintLink} onPress={handleUseDemoJson}>
              Or tap here to load Demo Paracetamol JSON ✓
            </Text>
          )}

          {measurements && (
            <View style={styles.successBadge}>
              <Text style={styles.successText}>Sensor data loaded ✓</Text>
            </View>
          )}

          <PrimaryButton
            title="Start Analysis"
            onPress={handleStartAnalysis}
            style={styles.actionBtn}
          />
        </View>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: TomatoTheme.spacing.lg,
    backgroundColor: TomatoTheme.colors.background,
  },
  section: {
    width: '100%',
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    color: TomatoTheme.colors.textPrimary,
    marginBottom: 6,
  },
  instruction: {
    fontSize: 15,
    color: TomatoTheme.colors.textSecondary,
    lineHeight: 22,
    marginBottom: TomatoTheme.spacing.lg,
  },
  uploadCard: {
    marginBottom: TomatoTheme.spacing.md,
  },
  demoHintLink: {
    fontSize: 14,
    fontWeight: '600',
    color: TomatoTheme.colors.primary,
    textAlign: 'center',
    marginBottom: TomatoTheme.spacing.lg,
    textDecorationLine: 'underline',
  },
  successBadge: {
    backgroundColor: TomatoTheme.colors.successLight,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: TomatoTheme.borderRadius.md,
    alignItems: 'center',
    marginBottom: TomatoTheme.spacing.lg,
  },
  successText: {
    color: TomatoTheme.colors.success,
    fontSize: 15,
    fontWeight: '700',
  },
  actionBtn: {
    marginTop: TomatoTheme.spacing.md,
  },
});
